### PR TITLE
build: add conanfile to create conan package

### PR DESCRIPTION
**Pull request by gocarlos**

### CODE REVIEW

**Comment by gocarlos** [comment]
@jimsch please review those changes

**Comment by jimsch** [comment]
Can you give me some idea of what this is doing?

**Comment by gocarlos** [comment]
You can now do: `make install` and the consumer can do `find_package(cn-cbor)` to use this package.
Needed for e.g. vcpkg or yocto

**Comment by gocarlos** [comment]
The conanfile can be used to package this lib as a conan package

**Pull request merged**
